### ISSUE TITLE
AttributeError: 'module' object has no attribute 'OBConformerSearch'

### ISSUE THREAD

**Issue by schneiderfelipe** [dudektria/pnictogen#6]
Some tests at Travis are failing due to:

    AttributeError: 'module' object has no attribute 'OBConformerSearch'

It seems that the OpenBabel version provided by Travis (`libopenbabel4 amd64 2.3.2+dfsg-1.1` and `libopenbabel-dev amd64 2.3.2+dfsg-1.1` at Ubuntu 14.04.5 LTS) has no support for conformer search.

**Comment by berquist** [comment]
I searched through the Open Babel code + wrapper and had a hard time figuring it out. I think I'm using 2.4.1 locally and also have this problem. Do you know which version you're using?

**Comment by dudektria** [comment]
I remember now. I compiled version 2.4.1 with [Eigen](http://eigen.tuxfamily.org/) (`libeigen2-dev`). From [here](http://open-babel.readthedocs.io/en/latest/Installation/install.html#compiling-open-babel),

>(...)
>The following are optional when compiling Open Babel, but if not available some features will be missing:
>(...)
> - **Eigen** version 2 or newer is **required** if using the language bindings in the release. In addition, if it not present, some API classes (OBAlign, OBConformerSearch) and plugins (the QEq and QTPIE charge models, the `--conformer` and `--align` operations) will not be available.
>
>(...)

I get no errors when I run `python setup.py -v nosetests` locally ([complete output here](https://gist.github.com/dudektria/b781a39ab39f440b17c59a004f05e8e8)):

    Ran 18 tests in 9.536s

    OK

I'm not sure here. Should we remove support for conformer search? Or should we use a `try ... except` to test if support exists?

**Comment by berquist** [comment]
If you want the conformer search to stay a part of the project, then it should be tested. Either

1. Open Babel can be compiled from source rather than using the old package manager version, or
2. maybe a version on conda exists that has been compiled this way.

Option 1 is not great since it takes so long. I can investigate number 2, and maybe make a new conda package if the right one doesn't exist.

On the other hand, conformer search is tested, but the test doesn't necessarily have anything to do with template generation. Maybe a try/except, or if nose has skip functionality. I don't really know.

**Comment by dudektria** [comment]
Great, I will try something along try/except or skip, but I don't have much familiarity with conda packages.
